Autogenerated tree updates.
merged:

  gentoo-staging-nov-2021: a15a64f48741a493e49dfee7d4280a3dc10cd21d
  flora: 523a446b976b43c4ede7fd49048643aaf4812e42
  faustoo: bce9c54c8ef4c530104d05c1d279ecefba5afd8d
  deadbeef: 53e0a41db6e7193bd83ef117f8055457f0990cb7
  gentoo-staging: 9292583023a6610905c79a4707db3ac6c63b3a31
  kit-fixups: 462069c28afbee8ad755e667bb90e360e926ac4a

diff --git a/media-sound/rosegarden/templates/rosegarden.tmpl b/media-sound/rosegarden/templates/rosegarden.tmpl
--- a/media-sound/rosegarden/templates/rosegarden.tmpl
+++ b/media-sound/rosegarden/templates/rosegarden.tmpl
@@ -1,17 +1,17 @@
-# Copyright 1999-2019 Gentoo Authors
 # Distributed under the terms of the GNU General Public License v2
 
 EAPI=7
 
-inherit cmake-utils xdg
+inherit cmake xdg virtualx
 
 DESCRIPTION="MIDI and audio sequencer and notation editor"
 HOMEPAGE="https://www.rosegardenmusic.com/"
-SRC_URI="mirror://sourceforge/${PN}/${P}.tar.bz2"
+SRC_URI="{{artifacts[0].src_uri}}"
+#SRC_URI="mirror://sourceforge/${PN}/${P}.tar.bz2"
 
 LICENSE="GPL-2"
 SLOT="0"
-KEYWORDS="amd64 ~ppc x86"
+KEYWORDS="*"
 IUSE="lirc"
 
 BDEPEND="
@@ -41,14 +41,27 @@ RDEPEND="
 DEPEND="${RDEPEND}
 	dev-qt/qttest:5
 "
+post_src_unpack() {
+    if [ ! -d "${S}" ] ; then
+        mv ${WORKDIR}/{{github_user}}-* ${S} || die
+    fi
+}
 
 src_prepare() {
-	cmake-utils_src_prepare
+	cmake_src_prepare
 }
 
 src_configure() {
 	local mycmakeargs=(
-		"-DDISABLE_LIRC=$(usex lirc OFF ON)"
+		-DDISABLE_LIRC=$(usex !lirc)
 	)
-	cmake-utils_src_configure
+	cmake_src_configure
+}
+
+src_test() {
+	# bug 701682, tries to open network socket and fails.
+	local myctestargs=(
+		-E "(test_notationview_selection)"
+	)
+	virtx cmake_src_test
 }
